

GET http://localhost:8800/test/cats
Content-Type: application/json; charset=UTF-8


###

GET http://localhost:8800/test/cat/fsduifh
Content-Type: application/json; charset=UTF-8

###

POST http://localhost:8800/test/cat  HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
      "id": "weju0fj20qj222",
      "name": "red",
      "age": 2,
      "species": "Sharm",
      "isCute": false,
      "friends": []
}